pipeline {
    agent {
        docker {
            image 'python:latest'
            args '--user root'
        }
    }

    stages {
        stage('build') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling python app'
                dir('vote'){
                        sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit Tests on python app'
                dir('vote'){
                    sh 'nosetests -v'
                }
            }
        }
    }
    post {
        always{
            echo 'Build pipeline for vote is complete...'

        }
        failure{
            slackSend (channel: "instavote-cd",message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success{
            slackSend (channel: "instavote-cd",message: "Build Succeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
