pipeline {
    agent any

    tools {
        maven 'Maven 3.8.1'
    }

    stages {
        stage('build') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                        sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package'
                }
            }
        }
    }
    post {
        always{
            echo 'Build pipeline for worker is complete...'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true

        }
    }
}
